### ISSUE TITLE
Issue with running nodemon

### ISSUE THREAD

**Issue by SonamTandinWang** [SonamTandinWang/GA-Project-2#1]
Was just refreshing the page and then got this error and cannot locate what I changed that broke everything. 

<img width="1199" alt="screen shot 2015-07-21 at 10 05 36 am" src="https://cloud.githubusercontent.com/assets/12677031/8802711/3f7a619c-2f91-11e5-9d2a-662721058e03.png">

**Comment by SonamTandinWang** [comment]
@WilliamfShaw

**Comment by SonamTandinWang** [comment]
My bad I forgot to tag you in the issue request.

**Comment by WilliamfShaw** [comment]
@SonamTandinWang  Need so much more information, Also this is a super nice error its giving you a line and everything. I believe you arent closing your html tags right bro bro. Look into that, let me know what you come up with

**Comment by SonamTandinWang** [comment]
@WilliamfShaw i fixed it.
